In [1]:
from sklearn.metrics.pairwise import cosine_similarity
import torch
from transformers import AutoTokenizer, CLIPTextModel

/opt/conda/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
model = CLIPTextModel.from_pretrained("openai/clip-vit-base-patch32")
tokenizer = AutoTokenizer.from_pretrained("openai/clip-vit-base-patch32")

In [3]:
inputs = tokenizer(["a female with autism spectrum disorder", "a male with autism spectrum disorder"], padding=True, return_tensors="pt")
with torch.no_grad():
    outputs = model(**inputs)
last_hidden_state = outputs.last_hidden_state
pooled_output = outputs.pooler_output  # pooled (EOS token) states

X = [pooled_output[0].numpy()]
Y = [pooled_output[1].numpy()]
cosine_similarity(X, Y)

array([[0.8688332]], dtype=float32)

In [4]:
inputs = tokenizer(["a female with autism spectrum disorder", "a healthy female"], padding=True, return_tensors="pt")
with torch.no_grad():
    outputs = model(**inputs)
last_hidden_state = outputs.last_hidden_state
pooled_output = outputs.pooler_output  # pooled (EOS token) states

X = [pooled_output[0].numpy()]
Y = [pooled_output[1].numpy()]
cosine_similarity(X, Y)

array([[0.6291567]], dtype=float32)

In [5]:
inputs = tokenizer(["a female with autism spectrum disorder", "a healthy male"], padding=True, return_tensors="pt")
with torch.no_grad():
    outputs = model(**inputs)
last_hidden_state = outputs.last_hidden_state
pooled_output = outputs.pooler_output  # pooled (EOS token) states

X = [pooled_output[0].numpy()]
Y = [pooled_output[1].numpy()]
cosine_similarity(X, Y)

array([[0.555942]], dtype=float32)